### ISSUE TITLE
error with ./launcher-gnu.sh

### ISSUE THREAD

**Issue by cbiOPela** [BSGOxford/BrowseVCF#3]
Hi all! 

Trying to use your fantastic tool in a Linux VM, i get this error when running ./launcher-gnu.sh script.
I follow the instructions in the readme file and i get the same error when compiling from source or through the easy way...
Could you please give me some advice?

Thank you in advance

I paste the error message:

`:~/Software/web$` ./launcher-gnu.sh
/home/viviangs/Software/web/../python27gnu/bin:/home/viviangs/.local/bin:/home/viviangs/miniconda/condabin:/home/viviangs/Software/Miniconda/miniconda2/pkgs/mosdepth-0.2.5-hb763d49_0/bin:/home/viviangs/Software/Miniconda/miniconda2/pkgs/mosdepth-0.2.5-hb763d49_0/bin:/home/viviangs/Software/Miniconda/miniconda2/pkgs/mosdepth-0.2.5-hb763d49_0/bin/htslib-1.9:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/viviangs/Software/ngscat.v0.1:/home/viviangs/Software/ngscat.v0.1:/home/viviangs/Software/ngscat.v0.1
Python 2.7.11
ARGS: ['launcher-cherrypy.py', '/home/viviangs/Software/web/../python27gnu/bin/python']
PROCS: None
[31/Jul/2019:09:17:16] ENGINE Bus STARTING
Traceback (most recent call last):
  File "launcher-cherrypy.py", line 220, in <module>
    main()
  File "launcher-cherrypy.py", line 207, in main
    app = GUIApp()
  File "launcher-cherrypy.py", line 77, in __init__
    tk.Frame.__init__(self, master)
  File "/home/viviangs/Software/python27gnu/lib/python2.7/lib-tk/Tkinter.py", line 2569, in __init__
    Widget.__init__(self, master, 'frame', cnf, {}, extra)
  File "/home/viviangs/Software/python27gnu/lib/python2.7/lib-tk/Tkinter.py", line 2081, in __init__
    BaseWidget._setup(self, master, cnf)
  File "/home/viviangs/Software/python27gnu/lib/python2.7/lib-tk/Tkinter.py", line 2056, in _setup
    _default_root = Tk()
  File "/home/viviangs/Software/python27gnu/lib/python2.7/lib-tk/Tkinter.py", line 1814, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable
[31/Jul/2019:09:17:16] ENGINE Started monitor thread 'Autoreloader'.
/home/viviangs/Software/python27gnu/lib/python2.7/site-packages/cherrypy/process/wspbus.py:231: RuntimeWarning: The main thread is exiting, but the Bus is in the states.STARTING state; shutting it down automatically now. You must either call bus.block() after start(), or call bus.exit() before the main thread exits.
  "main thread exits." % self.state, RuntimeWarning)
[31/Jul/2019:09:17:16] ENGINE Bus STOPPING
[31/Jul/2019:09:17:16] ENGINE HTTP Server cherrypy._cpwsgi_server.CPWSGIServer(('127.0.0.1', 39357)) already shut down
[31/Jul/2019:09:17:16] ENGINE Stopped thread 'Autoreloader'.
[31/Jul/2019:09:17:16] ENGINE Bus STOPPED
[31/Jul/2019:09:17:16] ENGINE Bus EXITING
[31/Jul/2019:09:17:16] ENGINE Bus `EXITED`

**Comment by silvia-s** [comment]
Hi there,

We have never tested BrowseVCF on a VM, but from your error it looks like X11 is not set up.
When you log into your VM, you'll need to use `ssh -X`, as the `-X` is required to allow you to open windows (like an internet browser). If this doesn't work, perhaps X11 is not installed on the VM; to solve that, try installing `xauth` and `xterm` using the package manager.
Hope this solves your issue, let me know how it goes.

Cheers,
Silvia
