### ISSUE TITLE
Error when running ./launcher-gnu.sh

### ISSUE THREAD

**Issue by fierytortilla** [BSGOxford/BrowseVCF#6]
I downloaded the tarball of BrowseVCF and tried to run the script launcher-gnu.sh, but it keeps giving me the same error:

```
/home/azureuser/vcf-browsers/BrowseVCF/web/../python27gnu/bin:/home/azureuser/vcf-browsers/BrowseVCF/web/../python27gnu/bin:/home/azureuser/.local/bin:/sbin:/bin:/usr/bin:/usr/local/bin:/snap/bin
Python 2.7.11
ERROR:root:code for hash md5 was not found.

Traceback (most recent call last):
  File "/home/azureuser/vcf-browsers/BrowseVCF/python27gnu/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/home/azureuser/vcf-browsers/BrowseVCF/python27gnu/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type md5
ERROR:root:code for hash sha1 was not found.
Traceback (most recent call last):
  File "/home/azureuser/vcf-browsers/BrowseVCF/python27gnu/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/home/azureuser/vcf-browsers/BrowseVCF/python27gnu/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha1
ERROR:root:code for hash sha224 was not found.
Traceback (most recent call last):
  File "/home/azureuser/vcf-browsers/BrowseVCF/python27gnu/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/home/azureuser/vcf-browsers/BrowseVCF/python27gnu/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha224
ERROR:root:code for hash sha256 was not found.
Traceback (most recent call last):
  File "/home/azureuser/vcf-browsers/BrowseVCF/python27gnu/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/home/azureuser/vcf-browsers/BrowseVCF/python27gnu/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha256
ERROR:root:code for hash sha384 was not found.
Traceback (most recent call last):
  File "/home/azureuser/vcf-browsers/BrowseVCF/python27gnu/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/home/azureuser/vcf-browsers/BrowseVCF/python27gnu/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha384
ERROR:root:code for hash sha512 was not found.
Traceback (most recent call last):
  File "/home/azureuser/vcf-browsers/BrowseVCF/python27gnu/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/home/azureuser/vcf-browsers/BrowseVCF/python27gnu/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha512
Traceback (most recent call last):
  File "launcher-cherrypy.py", line 5, in <module>
    import cherrypy
  File "/home/azureuser/vcf-browsers/BrowseVCF/python27gnu/lib/python2.7/site-packages/cherrypy/__init__.py", line 72, in <module>
    from cherrypy import _cptools
  File "/home/azureuser/vcf-browsers/BrowseVCF/python27gnu/lib/python2.7/site-packages/cherrypy/_cptools.py", line 256, in <module>
    from cherrypy.lib import cptools, encoding, auth, static, jsontools
  File "/home/azureuser/vcf-browsers/BrowseVCF/python27gnu/lib/python2.7/site-packages/cherrypy/lib/cptools.py", line 5, in <module>
    from hashlib import md5
ImportError: cannot import name md5`
```

I have tried googling the problem and it seems to be an issue with openssl, but I'm not sure if that is even the case. I have installed all the prerequisites mentioned. Any help would be most appreciated. I am on Ubuntu 20.04.

**Comment by silvia-s** [comment]
Hi, as stated in the README this software is no longer supported, but from a quick look at your error this seems to be an incompatibility between the `openssl` lib version of your OS (Ubuntu 20.04) and the `cherrypy` module shipped with BrowseVCF. Unfortunately, at the time of publishing this software, we only tested it on Ubuntu version 14.04, but I just checked on Ubuntu 18.04 and it works fine. Any chance you can run this on another PC, or using a VM with a previous version of Ubuntu? That might be easier/quicker than trying to troubleshoot packages and dependencies. 
Hope this helps!

**Comment by fierytortilla** [comment]
@silvia-s My apologies, I must have glanced over the line that mentioned that this was no longer supported. But yes it does seem the openssl in Ubuntu 20.04 is not compatible. I do want to work with it for some quick research purposes, so I will try it out on Ubuntu 18.04. Thanks for your help.
